{{- if .Values.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: backstage
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if or .Values.httpRoute.annotations .Values.commonAnnotations }}
  annotations:
    {{- if .Values.httpRoute.annotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.httpRoute.annotations "context" $) | nindent 4 }}
    {{- end }}
    {{- if .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  parentRefs:
    - group: {{ .Values.httpRoute.parentRefs.group | default "gateway.networking.k8s.io" }}
      kind: {{ .Values.httpRoute.parentRefs.kind | default "Gateway" }}
      name: {{ include "common.tplvalues.render" ( dict "value" .Values.httpRoute.parentRefs.name "context" $ ) }}
      {{- if .Values.httpRoute.parentRefs.namespace }}
      namespace: {{ include "common.tplvalues.render" ( dict "value" .Values.httpRoute.parentRefs.namespace "context" $ ) }}
      {{- end }}
      {{- if .Values.httpRoute.parentRefs.sectionName }}
      sectionName: {{ include "common.tplvalues.render" ( dict "value" .Values.httpRoute.parentRefs.sectionName "context" $ ) }}
      {{- end }}
  {{- if .Values.httpRoute.hostnames }}
  hostnames:
    {{- range .Values.httpRoute.hostnames }}
    - {{ include "common.tplvalues.render" ( dict "value" . "context" $ ) | quote }}
    {{- end }}
  {{- end }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: {{ .Values.httpRoute.path | default "/" }}
      backendRefs:
        - group: ""
          kind: Service
          name: {{ include "common.names.fullname" . }}
          port: {{ .Values.service.ports.backend }}
          weight: 1
    {{- if .Values.httpRoute.extraRules }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.httpRoute.extraRules "context" $ ) | nindent 4 }}
    {{- end }}
{{- end }}
